### ISSUE TITLE
Minification plugin causes error after webpack 5.10.1

### ISSUE THREAD

**Issue by meteorlxy** [privatenumber/esbuild-loader#86]
Things worked well in webpack v5.10.0, but started to fail after v5.10.1.

It still fails in the latest webpack v5.11.1

### Console error

```sh
Uncaught TypeError: (intermediate value)(intermediate value)(...) is not a function
    at runtime~app.38fb8d44.js:1
    at runtime~app.38fb8d44.js:3
```

### Corresponding snippet

![image](https://user-images.githubusercontent.com/18205362/103257003-5f897f00-49ca-11eb-8b85-464d5b38e9c4.png)

---

Let me know if the context is not enough, I'm willing to provide more information.

**Comment by privatenumber** [comment]
So this isn't a build-time failure but a run-time error, correct? If so, this might be a bug in esbuild, rather than esbuild-loader.

Do you happen to have minimal input code to reproduce this?

**Comment by meteorlxy** [comment]
Yes, it's a runtime error.

My webpack config is a little complicated, so I didn't have time to make a minimal repro.

I'll try to make one later

**Comment by privatenumber** [comment]
For what it's worth, I just added run-time tests [here](https://github.com/privatenumber/esbuild-loader/pull/89) and they all execute fine despite some minor compilation differences (mainly comments and mangling names).

**Comment by privatenumber** [comment]
@meteorlxy 

Closing this for now since it seems stale. Feel free to post your repro when you have one ready and I'll reopen.

Thanks

**Comment by jamespantalones** [comment]
FWIW, I'm having the same exact issue with `esbuild-loader 2.7.0` and `webpack 5.13.0`

When i downgrade to `webpack 5.10.0` the issue goes away

<img width="473" alt="Screen Shot 2021-01-13 at 2 13 01 PM" src="https://user-images.githubusercontent.com/4332285/104498354-93a79700-55a9-11eb-940f-83e0957b5d2a.png">

**Comment by privatenumber** [comment]
@jamespantalones 

Would you be able to provide minimal reproduction?

I'm interested in looking deeper into this but I can't do anything with the screenshots.
